Fix unused-variable Warning with NDEBUG
With NDEBUG the assert() is removed and the variable, that was checked
is unused:
    ../src/packet.h:45:11: error: unused variable ‘head’ [-Werror=unused-variable]